# Generated by Django 4.2 on 2024-09-16 17:20

from django.db import migrations
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=userauths.models.ShortUUIDField(default=userauths.models.ShortUUIDField.generate_shortuuid, max_length=22, unique=True),
        ),
    ]
