# Generated by Django 4.2 on 2024-09-16 17:38

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_profile_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=userauths.models.ShortUUIDField(default=userauths.models.ShortUUIDField.generate_shortuuid, max_length=22, unique=True),
        ),
    ]
